### ISSUE TITLE
Excludes in project file

### ISSUE THREAD

**Issue by thecodedrift** [jgillick/CodeSync#1]
Right now, it's hard coded (line 160) to use --exclude-cvs which is too restrictive on projects that have a nested tags directory. It should be possible to define the excludes in the project file and have those passed through.

Ref: http://rsync.samba.org/ftp/rsync/rsync.html
matches:

```
RCS SCCS CVS CVS.adm RCSLOG cvslog.* tags TAGS .make.state .nse_depinfo *~ #* .#* ,* _$* *$ *.old *.bak *.BAK *.orig *.rej .del-* *.a *.olb *.o *.obj *.so *.exe *.Z *.elc *.ln core .svn/ .git/ .hg/ .bzr/
```

Really it's just tags and TAGS that complicate things as those can be directory names normally.

**Comment by pacifisticuffs** [comment]
Ahh, that's why it doesn't download our tags! I was baffled by this.

**Comment by jgillick** [comment]
Oh damn, I haven't thought about this project in ages. Hi Jakob!
